migrate_files = [
    ".3gp",
    ".avi",
    ".f4v",
    ".flv",
    ".iso",
    ".m2ts",
    ".m4v",
    ".mkv",
    ".mov",
    ".mp4",
    ".mpeg",
    ".rm",
    ".rmvb",
    ".ts",
    ".vob",
    ".webm",
    ".wmv",
    ".strm",
    ".mpg",
]
migrate_subtitles = true
ignored_id_pattern = [
    '(144|240|360|480|720|1080)[Pp]',
    '[24][Kk]',
    '\w+2048\.com',
    'Carib(beancom)?',
    '[^a-z\d](f?hd|lt)[^a-z\d]',
]
capital = true
input_dir = "/path/to/input"
output_dir = "/path/to/output"
