[nodes.main]
script = "selector('.movie-list')"

[nodes.main.children.match_div]
script = "selector('.video-title>strong').val().delete('-').uppercase().equals(${crawl_name}).parent(2)"

[nodes.main.children.match_div.children.title]
script = "attr('title')"

[nodes.main.children.match_div.children.name]
script = "selector('.video-title>strong').val()"

[nodes.main.children.match_div.children.detail_url]
script = "attr('href').insert(0,${base_url})"
request = true

[nodes.main.children.match_div.children.detail_url.children.main_image]
script = "selector('.video-meta-panel>div>div.column.column-video-cover>a>img').attr('src')"

[nodes.main.children.match_div.children.detail_url.children.detail]
script = "selector('.panel-block>strong')"

[nodes.main.children.match_div.children.detail_url.children.detail.children.director]
script = "val().delete(' ').equals('導演:').next().val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.publisher]
script = "val().delete(' ').equals('發行:').next().val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.duration]
script = "val().delete(' ').equals('時長:').next().val().delete(' 分鍾')"

[nodes.main.children.match_div.children.detail_url.children.detail.children.series]
script = "val().delete(' ').equals('系列:').next().val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.actors]
script = "val().delete(' ').equals('演員:').next().selector('.female').prev().val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.tags]
script = "val().delete(' ').equals('類別:').next().selector('a').val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.makers]
script = "val().delete(' ').equals('片商:').next().val()"

[nodes.main.children.match_div.children.detail_url.children.detail.children.release_time]
script = "val().delete(' ').equals('日期:').next().val()"

[nodes.main.children.match_div.children.detail_url.children.detail_imgs]
script = "selector('.video-detail>.columns>.column>.message.video-panel>.message-body>.tile-images.preview-images>.tile-item').attr('href')"

[nodes.main.children.match_div.children.detail_url.children.detail_title]
script = "selector('.video-detail .current-title').val()"

[nodes.main.children.match_div.children.thumbnail]
script = "selector('img').attr('src')"